const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   INCREMENT_QUEUE_INDEX: "INCREMENT_QUEUE_INDEX",
   DECREMENT_QUEUE_INDEX: "DECREMENT_QUEUE_INDEX",
   RESET_QUEUE: "RESET_QUEUE",
   UPDATE_QUEUED_CARDS: "UPDATE_QUEUED_CARDS",
   STORE_EDITABLE_CARD: "STORE_EDITABLE_CARD",
   UPDATE_CREATABLE_CARD: "UPDATE_CREATABLE_CARD",
};

export default actions;
